version: "3"
services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        links:
            - php
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build: ./php/
        expose:
            - 9000
        links:
            - mysql
        volumes:
            - ./src:/var/www/html

    mysql:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - /var/lib/mysql
        ports:
           - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app_db
            MYSQL_USER: dev
            MYSQL_PASSWORD: secret
